### ISSUE TITLE
License

### ISSUE THREAD

**Issue by KottV** [jatinchowdhury18/NewMixer#98]
Hi,

I'd like to make NewMixer's binaries in open build server (actually, I did and it works), but there is a question about license. Regarding https://github.com/jatinchowdhury18/NewMixer/blob/master/Installer/NewMixer_License.txt it's custom proprietary license, so its not possible to put sources  on 3rd-side build servers. Or we can discuss it? :)

**Comment by jatinchowdhury18** [comment]
Hi Konstantin, thanks for looking into this. I've been considering switching to an open source license for some time. I'm not really sure what open source license would be the best for this specific project (GPL, MIT, etc). I'd be happy to hear any ideas you may have.

**Comment by KottV** [comment]
Cool!

I'm not good in opensource advocacy, there is resource with the list of licenses: https://opensource.org/licenses/category

Maybe if You declare your wishes and preferences, I can ask on some forums or mail-lists.

**Comment by jatinchowdhury18** [comment]
Awesome, I'll do some research and keep you posted what I end up doing. The main idea for me is that the code is open source and can be used by whomever, but that people using the software can use it to create music that they can then sell if they would like to. I'm worried that with GPL it would force anyone mixing with NewMixer to make all their songs Creative Commons or something like that.

I know Ardour uses the GPLv2, so that may be a good option for this project as well.

**Comment by KottV** [comment]
AFAIK, that all known software licenses cannot force anyone to publish the work's results (mixes, documents, images) under some boundaries, even GPL3.
Perhaps, this possible if You include in NewMixer the samples (.wav) under some strict copy rules.

**Comment by jatinchowdhury18** [comment]
From what I've read, I think you're correct. I've added a GPLv2 license for the whole repository (#99). I wasn't planning to upload a new version of the installer until I'm ready for the next release, but if you need that for uploading to the open build server let me know!

**Comment by KottV** [comment]
OBS supports Linux only, so LICENSE file is very thing.
